/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as EnterpriseRouteImport } from './routes/enterprise'
import { Route as GetStartedRouteImport } from './routes/get-started'
import { Route as HowItWorksRouteImport } from './routes/how-it-works'
import { Route as LiveSupportRouteImport } from './routes/live-support'
import { Route as LoginRouteImport } from './routes/login'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as ProviderRouteImport } from './routes/provider'
import { Route as ProvidersRouteImport } from './routes/providers'
import { Route as ResourcesRouteImport } from './routes/resources'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as SolutionsRouteImport } from './routes/solutions'
import { Route as SystemWatchRouteImport } from './routes/system-watch'
import { Route as DashboardIndexRouteImport } from './routes/dashboard.index'
import { Route as DashboardBillingRouteImport } from './routes/dashboard.billing'
import { Route as DashboardLiveSupportRouteImport } from './routes/dashboard.live-support'
import { Route as DashboardMessagesRouteImport } from './routes/dashboard.messages'
import { Route as DashboardSystemWatchRouteImport } from './routes/dashboard.system-watch'
import { Route as ProviderIndexRouteImport } from './routes/provider.index'
import { Route as DashboardRequestsIndexRouteImport } from './routes/dashboard.requests.index'
import { Route as DashboardRequestsRequestIdRouteImport } from './routes/dashboard.requests.$requestId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const EnterpriseRoute = EnterpriseRouteImport.update({
  id: '/enterprise',
  path: '/enterprise',
  getParentRoute: () => rootRouteImport,
} as any)
const GetStartedRoute = GetStartedRouteImport.update({
  id: '/get-started',
  path: '/get-started',
  getParentRoute: () => rootRouteImport,
} as any)
const HowItWorksRoute = HowItWorksRouteImport.update({
  id: '/how-it-works',
  path: '/how-it-works',
  getParentRoute: () => rootRouteImport,
} as any)
const LiveSupportRoute = LiveSupportRouteImport.update({
  id: '/live-support',
  path: '/live-support',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const ProviderRoute = ProviderRouteImport.update({
  id: '/provider',
  path: '/provider',
  getParentRoute: () => rootRouteImport,
} as any)
const ProvidersRoute = ProvidersRouteImport.update({
  id: '/providers',
  path: '/providers',
  getParentRoute: () => rootRouteImport,
} as any)
const ResourcesRoute = ResourcesRouteImport.update({
  id: '/resources',
  path: '/resources',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const SolutionsRoute = SolutionsRouteImport.update({
  id: '/solutions',
  path: '/solutions',
  getParentRoute: () => rootRouteImport,
} as any)
const SystemWatchRoute = SystemWatchRouteImport.update({
  id: '/system-watch',
  path: '/system-watch',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardBillingRoute = DashboardBillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardLiveSupportRoute = DashboardLiveSupportRouteImport.update({
  id: '/live-support',
  path: '/live-support',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardMessagesRoute = DashboardMessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardSystemWatchRoute = DashboardSystemWatchRouteImport.update({
  id: '/system-watch',
  path: '/system-watch',
  getParentRoute: () => DashboardRoute,
} as any)
const ProviderIndexRoute = ProviderIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProviderRoute,
} as any)
const DashboardRequestsIndexRoute = DashboardRequestsIndexRouteImport.update({
  id: '/requests/',
  path: '/requests/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardRequestsRequestIdRoute =
  DashboardRequestsRequestIdRouteImport.update({
    id: '/requests/$requestId',
    path: '/requests/$requestId',
    getParentRoute: () => DashboardRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/enterprise': typeof EnterpriseRoute
  '/get-started': typeof GetStartedRoute
  '/how-it-works': typeof HowItWorksRoute
  '/live-support': typeof LiveSupportRoute
  '/login': typeof LoginRoute
  '/pricing': typeof PricingRoute
  '/provider': typeof ProviderRouteWithChildren
  '/providers': typeof ProvidersRoute
  '/resources': typeof ResourcesRoute
  '/signup': typeof SignupRoute
  '/solutions': typeof SolutionsRoute
  '/system-watch': typeof SystemWatchRoute
  '/dashboard/billing': typeof DashboardBillingRoute
  '/dashboard/live-support': typeof DashboardLiveSupportRoute
  '/dashboard/messages': typeof DashboardMessagesRoute
  '/dashboard/system-watch': typeof DashboardSystemWatchRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/provider/': typeof ProviderIndexRoute
  '/dashboard/requests/$requestId': typeof DashboardRequestsRequestIdRoute
  '/dashboard/requests/': typeof DashboardRequestsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/enterprise': typeof EnterpriseRoute
  '/get-started': typeof GetStartedRoute
  '/how-it-works': typeof HowItWorksRoute
  '/live-support': typeof LiveSupportRoute
  '/login': typeof LoginRoute
  '/pricing': typeof PricingRoute
  '/providers': typeof ProvidersRoute
  '/resources': typeof ResourcesRoute
  '/signup': typeof SignupRoute
  '/solutions': typeof SolutionsRoute
  '/system-watch': typeof SystemWatchRoute
  '/dashboard/billing': typeof DashboardBillingRoute
  '/dashboard/live-support': typeof DashboardLiveSupportRoute
  '/dashboard/messages': typeof DashboardMessagesRoute
  '/dashboard/system-watch': typeof DashboardSystemWatchRoute
  '/dashboard': typeof DashboardIndexRoute
  '/provider': typeof ProviderIndexRoute
  '/dashboard/requests/$requestId': typeof DashboardRequestsRequestIdRoute
  '/dashboard/requests': typeof DashboardRequestsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/enterprise': typeof EnterpriseRoute
  '/get-started': typeof GetStartedRoute
  '/how-it-works': typeof HowItWorksRoute
  '/live-support': typeof LiveSupportRoute
  '/login': typeof LoginRoute
  '/pricing': typeof PricingRoute
  '/provider': typeof ProviderRouteWithChildren
  '/providers': typeof ProvidersRoute
  '/resources': typeof ResourcesRoute
  '/signup': typeof SignupRoute
  '/solutions': typeof SolutionsRoute
  '/system-watch': typeof SystemWatchRoute
  '/dashboard/billing': typeof DashboardBillingRoute
  '/dashboard/live-support': typeof DashboardLiveSupportRoute
  '/dashboard/messages': typeof DashboardMessagesRoute
  '/dashboard/system-watch': typeof DashboardSystemWatchRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/provider/': typeof ProviderIndexRoute
  '/dashboard/requests/$requestId': typeof DashboardRequestsRequestIdRoute
  '/dashboard/requests/': typeof DashboardRequestsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/enterprise'
    | '/get-started'
    | '/how-it-works'
    | '/live-support'
    | '/login'
    | '/pricing'
    | '/provider'
    | '/providers'
    | '/resources'
    | '/signup'
    | '/solutions'
    | '/system-watch'
    | '/dashboard/billing'
    | '/dashboard/live-support'
    | '/dashboard/messages'
    | '/dashboard/system-watch'
    | '/dashboard/'
    | '/provider/'
    | '/dashboard/requests/$requestId'
    | '/dashboard/requests/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/enterprise'
    | '/get-started'
    | '/how-it-works'
    | '/live-support'
    | '/login'
    | '/pricing'
    | '/providers'
    | '/resources'
    | '/signup'
    | '/solutions'
    | '/system-watch'
    | '/dashboard/billing'
    | '/dashboard/live-support'
    | '/dashboard/messages'
    | '/dashboard/system-watch'
    | '/dashboard'
    | '/provider'
    | '/dashboard/requests/$requestId'
    | '/dashboard/requests'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/enterprise'
    | '/get-started'
    | '/how-it-works'
    | '/live-support'
    | '/login'
    | '/pricing'
    | '/provider'
    | '/providers'
    | '/resources'
    | '/signup'
    | '/solutions'
    | '/system-watch'
    | '/dashboard/billing'
    | '/dashboard/live-support'
    | '/dashboard/messages'
    | '/dashboard/system-watch'
    | '/dashboard/'
    | '/provider/'
    | '/dashboard/requests/$requestId'
    | '/dashboard/requests/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  EnterpriseRoute: typeof EnterpriseRoute
  GetStartedRoute: typeof GetStartedRoute
  HowItWorksRoute: typeof HowItWorksRoute
  LiveSupportRoute: typeof LiveSupportRoute
  LoginRoute: typeof LoginRoute
  PricingRoute: typeof PricingRoute
  ProviderRoute: typeof ProviderRouteWithChildren
  ProvidersRoute: typeof ProvidersRoute
  ResourcesRoute: typeof ResourcesRoute
  SignupRoute: typeof SignupRoute
  SolutionsRoute: typeof SolutionsRoute
  SystemWatchRoute: typeof SystemWatchRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/enterprise': {
      id: '/enterprise'
      path: '/enterprise'
      fullPath: '/enterprise'
      preLoaderRoute: typeof EnterpriseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/get-started': {
      id: '/get-started'
      path: '/get-started'
      fullPath: '/get-started'
      preLoaderRoute: typeof GetStartedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/how-it-works': {
      id: '/how-it-works'
      path: '/how-it-works'
      fullPath: '/how-it-works'
      preLoaderRoute: typeof HowItWorksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/live-support': {
      id: '/live-support'
      path: '/live-support'
      fullPath: '/live-support'
      preLoaderRoute: typeof LiveSupportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/provider': {
      id: '/provider'
      path: '/provider'
      fullPath: '/provider'
      preLoaderRoute: typeof ProviderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/providers': {
      id: '/providers'
      path: '/providers'
      fullPath: '/providers'
      preLoaderRoute: typeof ProvidersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resources': {
      id: '/resources'
      path: '/resources'
      fullPath: '/resources'
      preLoaderRoute: typeof ResourcesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/solutions': {
      id: '/solutions'
      path: '/solutions'
      fullPath: '/solutions'
      preLoaderRoute: typeof SolutionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/system-watch': {
      id: '/system-watch'
      path: '/system-watch'
      fullPath: '/system-watch'
      preLoaderRoute: typeof SystemWatchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/billing': {
      id: '/dashboard/billing'
      path: '/billing'
      fullPath: '/dashboard/billing'
      preLoaderRoute: typeof DashboardBillingRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/live-support': {
      id: '/dashboard/live-support'
      path: '/live-support'
      fullPath: '/dashboard/live-support'
      preLoaderRoute: typeof DashboardLiveSupportRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/messages': {
      id: '/dashboard/messages'
      path: '/messages'
      fullPath: '/dashboard/messages'
      preLoaderRoute: typeof DashboardMessagesRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/system-watch': {
      id: '/dashboard/system-watch'
      path: '/system-watch'
      fullPath: '/dashboard/system-watch'
      preLoaderRoute: typeof DashboardSystemWatchRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/provider/': {
      id: '/provider/'
      path: '/'
      fullPath: '/provider/'
      preLoaderRoute: typeof ProviderIndexRouteImport
      parentRoute: typeof ProviderRoute
    }
    '/dashboard/requests/': {
      id: '/dashboard/requests/'
      path: '/requests'
      fullPath: '/dashboard/requests/'
      preLoaderRoute: typeof DashboardRequestsIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/requests/$requestId': {
      id: '/dashboard/requests/$requestId'
      path: '/requests/$requestId'
      fullPath: '/dashboard/requests/$requestId'
      preLoaderRoute: typeof DashboardRequestsRequestIdRouteImport
      parentRoute: typeof DashboardRoute
    }
  }
}

interface DashboardRouteChildren {
  DashboardBillingRoute: typeof DashboardBillingRoute
  DashboardLiveSupportRoute: typeof DashboardLiveSupportRoute
  DashboardMessagesRoute: typeof DashboardMessagesRoute
  DashboardSystemWatchRoute: typeof DashboardSystemWatchRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
  DashboardRequestsRequestIdRoute: typeof DashboardRequestsRequestIdRoute
  DashboardRequestsIndexRoute: typeof DashboardRequestsIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardBillingRoute: DashboardBillingRoute,
  DashboardLiveSupportRoute: DashboardLiveSupportRoute,
  DashboardMessagesRoute: DashboardMessagesRoute,
  DashboardSystemWatchRoute: DashboardSystemWatchRoute,
  DashboardIndexRoute: DashboardIndexRoute,
  DashboardRequestsRequestIdRoute: DashboardRequestsRequestIdRoute,
  DashboardRequestsIndexRoute: DashboardRequestsIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

interface ProviderRouteChildren {
  ProviderIndexRoute: typeof ProviderIndexRoute
}

const ProviderRouteChildren: ProviderRouteChildren = {
  ProviderIndexRoute: ProviderIndexRoute,
}

const ProviderRouteWithChildren = ProviderRoute._addFileChildren(
  ProviderRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRouteWithChildren,
  EnterpriseRoute: EnterpriseRoute,
  GetStartedRoute: GetStartedRoute,
  HowItWorksRoute: HowItWorksRoute,
  LiveSupportRoute: LiveSupportRoute,
  LoginRoute: LoginRoute,
  PricingRoute: PricingRoute,
  ProviderRoute: ProviderRouteWithChildren,
  ProvidersRoute: ProvidersRoute,
  ResourcesRoute: ResourcesRoute,
  SignupRoute: SignupRoute,
  SolutionsRoute: SolutionsRoute,
  SystemWatchRoute: SystemWatchRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
